app:
  db_link: "http://webzato.com/fms/fms_structure_10012018.zip"
  file_path: "fms_structure_10012018/fms_structure_10012018.csv"
  charset: "windows-1251"

spring:
  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/fms_branch_registry"
    username: "fms_branch_registry"
    password: "mt6LX4Y7F7a2CJwVqkAb"
    driver-class-name: "com.mysql.jdbc.Driver"